### ISSUE TITLE
Failed to import the required Python library

### ISSUE THREAD

**Issue by SaymonDzen** [nickjj/ansible-docker#107]
When trying to start docker compose on clean host ubuntu cloud 20.04
```
TASK [Create and start services on Docker-compose] *****************************
fatal: [monitoring-stage.e]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (Docker SDK for Python: docker above 5.0.0 (Python >= 3.6) or docker before 5.0.0 (Python 2.7) or docker-py (Python 2.6)) on monitoring-stage's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` (Python >= 3.6) or `pip install docker==4.4.4` (Python 2.7) or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'"}
```

**Comment by nickjj** [comment]
Hi,

What version of Python do you have installed?

**Comment by SaymonDzen** [comment]
HI
ansible_python_interpreter=/usr/bin/python3
ls -la /usr/bin/python3
lrwxrwxrwx 1 root root 9 Mar 13  2020 /usr/bin/python3 -> python3.8

**Comment by nickjj** [comment]
The `Create and start services on Docker-compose` isn't a part of this role.

How are you starting Docker Compose in that task?

Have you checked the README about using the `docker_*` modules? https://github.com/nickjj/ansible-docker#working-with-ansibles-docker_-modules

Do you get the same error if you run `docker-compose up` on your server directly?

**Comment by SaymonDzen** [comment]
```
    - name: Create and start services on Docker-compose
      community.docker.docker_compose:
        project_src: "/opt/erlymon/"
```
if you run directly, then no errors are displayed
```
docker-compose -v
docker-compose version 1.29.2, build unknown

docker-compose -f /opt/erlymon/docker-compose.yml up
Creating network "erlymon_default" with the default driver
Creating volume "erlymon_prometheus_data" with default driver
Creating volume "erlymon_grafana_data" with default driver
Pulling prometheus (prom/prometheus:latest)...
...
````

**Comment by nickjj** [comment]
Check the readme link I supplied.

**Comment by SaymonDzen** [comment]
I added vars ansible_python_interpreter in task, nothing has changed 
```
    - name: Create and start services on Docker-compose
      community.docker.docker_compose:
        project_src: "/opt/erlymon/"
      vars:
        ansible_python_interpreter: "/usr/bin/env python3-docker"
```

**Comment by SaymonDzen** [comment]
I was wrong, that's another task! Thank you very much for your help and patience.

**Comment by nickjj** [comment]
No problem, I'm guessing it's all working now?

**Comment by SaymonDzen** [comment]
Yes, everything works with this. Thank you! Now installing the role on a clean host (exactly the role  - task from examply) I encountered apt problem. 
```
TASK [nickjj.docker : Install Docker's dependencies] ***************************
fatal: [monitoring-stage.e]: FAILED! => {"cache_update_time": 1622726890, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'apt-transport-https' 'gnupg2' 'software-properties-common' 'gcc' 'python3-dev' 'python3-pip' 'virtualenv'' failed: E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. \n", "rc": 100, "stderr": "E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. \n", "stderr_lines": ["E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. "], "stdout": "", "stdout_lines": []}
````
dpkg --configure -a on host resolved this promblem.  This is probably a problem with the ubuntu repositories. A couple of hours ago, from that virtual machine template with cloudinit, I did not observe this problem

**Comment by nickjj** [comment]
Typically a fresh host would have `sudo apt-get update` run on it before installing Ansible, perhaps through a dedicated bootstrap role.

That's why this role doesn't run the update itself. IMO this is an anti-pattern of Ansible roles to run an apt update in every role, or define a cache timeout, it's something I used to do 5 years ago but stopped.
