### ISSUE TITLE
Update apt cache before installing packages

### ISSUE THREAD

**Issue by gthieleb** [nickjj/ansible-docker#108]
In recent versions of debian it is required to update the package cache before installation of further packages is possible.

Please add the ```update_cache: true``` to the apt module parameters.

https://github.com/nickjj/ansible-docker/blob/a284dde4e0fa36c2be97c416e4e0eb6deedf28f8/tasks/main.yml#L19

**Comment by nickjj** [comment]
Hi,

Thanks but this has been discussed in the past in https://github.com/nickjj/ansible-docker/pull/59#issuecomment-513504141.
