### ISSUE TITLE
docker not installed into /usr/local/bin

### ISSUE THREAD

**Issue by cdaringe** [nickjj/ansible-docker#119]
# Problem

`docker` is not available to my user even though `docker-compose` is.

# Research

role output:

```
TASK [nickjj.docker : Symlink selected Python package binaries to /usr/local/bin] *************************************
skipping: [###.###.#.###] => (item={'name': 'docker', 'state': 'present'}) 
```

```
# ls /usr/local/bin/docker
ls: cannot access '/usr/local/bin/docker': No such file or directory
```

something about the role thinks docker has already been linked in on my target machine's /usr/local/bin, when it's missing

**Comment by nickjj** [comment]
Docker gets installed to `/usr/bin/docker`.

The symlink is only for Python packages. The Docker Compose Python package is the `docker-compose` binary. The Docker Python package isn't a callable binary, it's only a library -- more specifically a library that needs to exist for tools like Ansible to use any `docker_*` modules.

**Comment by cdaringe** [comment]
hey @nickjj , thanks for the feedback. i'm deploying to an ubuntu server:

```
$ droppy:~# ls /usr/bin/docker
dockerd       docker-init   docker-proxy 
```

can you point me to the step that installs the binary? i'm finding that its just plain absent. i want to better understand why ansible thinks it can be skipped, when the binary is clearly missing

**Comment by cdaringe** [comment]
I found the step. i can debug solo. thx!

**Comment by nickjj** [comment]
You wrote:

```
TASK [nickjj.docker : Symlink selected Python package binaries to /usr/local/bin] *************************************
skipping: [###.###.#.###] => (item={'name': 'docker', 'state': 'present'}) 
```

This task is unrelated to the Docker binary (check my previous comment for a breakdown).

This role will apt install Docker with the `Install Docker and Docker Compose v2` task.

I'm not sure what your system's state is but you can `sudo apt-get remove --purge docker*` and then try running this role again. Then you should be able to run `which docker` to see it in `/usr/bin`.
