### ISSUE TITLE
Version numbers on Galaxy

### ISSUE THREAD

**Issue by damongant** [nickjj/ansible-docker#12]
Hey, just wanted to mention that Galaxy will by default hand you the highest and not the latest uploaded version, so you'll end up with 17.12 (where it's still `docker_opts`, that took me a while to debug :) )

Unfortunately I have no suggestion what to do here since I've never published a Galaxy package.

**Comment by nickjj** [comment]
Oh wow, I didn't notice that, thanks.

I just deleted both of the 17.x tags from both github and the galaxy, so it should work now.

It was either that or start rewriting tag history.

On the bright side, 18.03 is considered a stable release so it shouldn't cause any issues. For anyone reading this, if you really need to drop down to 17.12 or 17.06 you can still define those versions in your inventory's variables (to overwrite my defaults) and things will work as expected.
