### ISSUE TITLE
Setting ansible_python_interpreter to "/usr/bin/env python3-docker" causes not found error

### ISSUE THREAD

**Issue by mherold** [nickjj/ansible-docker#128]
The README (https://github.com/nickjj/ansible-docker/blob/v2.4.0/README.md#working-with-ansibles-docker_-modules) mentions to set `ansible_python_interpreter: "/usr/bin/env python3-docker"`, but that causes a `bin/sh: 1: /usr/bin/env python3-docker: not found` error with the current ansible version (10.1.0, ansible-core 2.17.1).

There's some discussion about it here: ansible/ansible#83476

For me, it works for now when changing it to the explicit path to the script: `ansible_python_interpreter: "/usr/local/bin/python3-docker"`.

**Comment by nickjj** [comment]
Thanks for opening this and proposing a solution.

**Comment by nickjj** [comment]
This has been addressed in v2.5.0 which is available.
