### ISSUE TITLE
Can't upgrade to edge release.

### ISSUE THREAD

**Issue by lexa-uw** [nickjj/ansible-docker#17]
Apt repo has:
```
Package: docker-ce
Architecture: amd64
Version: 18.04.0~ce~3-0~debian
```
I'm trying update with option `docker_version: "18.04.0`

Error:
```
Version '18.04.0~ce-0~debian' for 'docker-ce' was not found
```

Problem on [line 36](https://github.com/nickjj/ansible-docker/blob/d786ad1a5ec3a46a154c9ffd72d737be73ec9a2b/tasks/main.yml#L36)

**Comment by nickjj** [comment]
Hmm. Looks like Docker changed their package name formatting again.

18.04 doesn't match up with the others as seen here:  
https://download.docker.com/linux/ubuntu/dists/xenial/pool/edge/amd64/

Thanks for the report. I may end up adjusting the role to make this configurable.

**Comment by lexa-uw** [comment]
👍

**Comment by nickjj** [comment]
Just pushed `v0.2.3` to the Galaxy which exposes a new variable to deal with this package change. I also updated Docker to 18.04 and Compose to 1.21.0.

**Comment by lexa-uw** [comment]
Thank you!
