### ISSUE TITLE
Installation of docker compose without using pip fails

### ISSUE THREAD

**Issue by NateV** [nickjj/ansible-docker#24]
Hi,
Nice work here. I was trying to install docker-compose the way you do here (and the way Docker recommends) with `curl`. But I kept running into errors about the `compose` module not being available, which I finally solved by installing docker-compose with pip.

How'd you avoid that problem? 

Thanks!

**Comment by nickjj** [comment]
Hi,

What OS are you using? What was the state of the system before you installed Docker / Compose?

I never experienced that issue. Just using this role should be good enough to get up and running with no additional installation steps.

**Comment by NateV** [comment]
Hmm. I'm using ubuntu xenial. Its possible there's conflicting python modules. I imagine your playbook assumes a machine that didn't have docker-py or docker python modules installed with pip. My machine is a little messy. The `pip install` approach has worked now, and its probably best for me just be happy with that, rather than trying to keep digging at this. Thanks!

**Comment by nickjj** [comment]
My playbook consists of bootstrapping a machine to run Ansible, doing a few other system related things, installing Docker / Docker Compose with this role and then running my Dockerized applications.

I have never installed `docker-py`.

You might want to run `which docker-compose` to see if it's using the curl version or your pip version.
