### ISSUE TITLE
docker_daemon_options via daemon.json

### ISSUE THREAD

**Issue by riteshpuj2013** [nickjj/ansible-docker#31]
Hi,

As mentioned on the official docker page, its recommended to pass `docker daemon options` using daemon.json file instead of passing them on the command line.

I can create a PR which copies the daemon.json file from "files" directory to `/etc/docker/daemon.json` and provides a variable `include_docker_daemon_file: True or False` in defaults/main.yml. The user can just enter all daemon options in that file. 
For eg:
`{
  "insecure-registries" : ["example.com:5000"],
  "live-restore": true
}
`
If variable's value is `True`, the script would include the file and if `False` the script would remove the file.

Would this be a PR of interest to you?

For your reference:
https://docs.docker.com/config/containers/live-restore/#enable-live-restore

> If you prefer, you can start the dockerd process manually with the --live-restore flag. This approach is not recommended because it does not set up the environment that systemd or another process manager would use when starting the Docker process. This can cause unexpected behavior.

Best Regards,
Ritesh Puj

**Comment by riteshpuj2013** [comment]
Yes @nickjj, that makes sense.
Thank you for the info.

**Comment by nickjj** [comment]
No problem. On paper, writing out the json file is a better solution but I do feel it complicates things for little benefit in this specific case.

**Comment by nickjj** [comment]
Configuration is now done in `/etc/docker/daemon.json` as of v1.1.0.

**Comment by riteshpuj2013** [comment]
Thanks for the info and sharing the code @nickjj.
