### ISSUE TITLE
Cleanup in cron.d file

### ISSUE THREAD

**Issue by benyanke** [nickjj/ansible-docker#35]
It would be nice to have cron_tasks.cron_file as an option, which would place the docker cleanup work in a cron.d file, allowing easier administration for those who prefer to use this construct.

**Comment by nickjj** [comment]
Good idea. Going to leave this open until it's addressed, but it's likely not worth creating a new release over by itself.

**Comment by nickjj** [comment]
This is now included in v1.4.0.
