### ISSUE TITLE
Installation fails on Ubuntu 17.10 'Artful'

### ISSUE THREAD

**Issue by compiaffe** [nickjj/ansible-docker#4]
When doing an installation on localhost using the following playbook:

```---
- hosts: all #realsense-docker-hosts
  tasks:
  - include_role:
      name: nickjj.docker
    tags:
      - docker
    become: true
    become_method: sudo

    vars:
      docker_edition: 'ce'
      docker_channel: 'edge'
      docker_install_docker_compose: true
```
executed with:
```ansible-playbook -i "localhost," -c local -K playbook.yaml
```

The installation fails with:

```TASK [nickjj.docker : Install Docker] ***********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'docker-engine' is available"}
```

When trying to install it manually using:
```apt-get install docker-engine```

it mentions a rename:
```sudo apt-get install docker-engine                         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-engine is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  docker-ce
```

**Comment by nickjj** [comment]
Hi,

What version of this role are you running? `docker-engine` hasn't been used in many many many months.

There's a v17.06 version of the role that uses `docker-ce` (or `ee` if you happen to configure that).

**Comment by nickjj** [comment]
Ok I see what happened here. I remember now. I tagged it prematurely and the commit that changed that never made its way into what was tagged on the Ansible Galaxy.

I just updated the role to default to Docker v17.12 / Compose 1.18 and it's available on the Galaxy. If you update your role it should work now.

Please confirm and close if it works.

**Comment by compiaffe** [comment]
Hi, thank you for the quick response. All working now, thank you :)

**Comment by nickjj** [comment]
Nice and no problem.
