### ISSUE TITLE
Second run for playbook with this role errors due to apt downgrade

### ISSUE THREAD

**Issue by jamesalford** [nickjj/ansible-docker#5]
Include of role:
```
- name: "Install Docker"
  include_role:
    name: nickjj.docker
```

Error:
```
TASK [nickjj.docker : Install Docker] *****************************************************************************************************************************************************************
fatal: [dev-local-ansible-1]: FAILED! => {
    "cache_update_time": 1518626749,
    "cache_updated": false,
    "changed": false,
    "rc": 100
}

STDOUT:
Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  pigz
Use 'sudo apt autoremove' to remove it.
Recommended packages:
  aufs-tools cgroupfs-mount | cgroup-lite
The following packages will be DOWNGRADED:
  docker-ce
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.

STDERR:
E: Packages were downgraded and -y was used without --allow-downgrades.

MSG:

'/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"     install 'docker-ce=18.01.0~ce-0~ubuntu' -o APT::Install-Recommends=no' failed: E: Packages were downgraded and -y was used without --allow-downgrades.
```

version that gets installed on run 1:
```
dpkg -l |grep docker-ce
ii  docker-ce                             18.02.0~ce-0~ubuntu                        amd64        Docker: the open-source application container engine
```

Ubuntu version:
```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

**Comment by nickjj** [comment]
Were you changing around versions of Docker?

Downgrades are an entirely different problem and this role doesn't support it. If you want to move from 18.02 down to 17.12 or something like that then you would be responsible for running `sudo apt-get remove --purge docker-ce` before running this role.

**Comment by jamesalford** [comment]
I will run everything again without this role and make sure docker isn’t installed however as far as I know we aren’t. So run one of this role installs the default and then nothing is changed before run 2

**Comment by nickjj** [comment]
Yeah check it out.

The role has tests which run on Travis. Here's a successful run from yesterday (on the commit that made the v18.02 default release):

https://travis-ci.org/nickjj/ansible-docker/jobs/341424391

It runs the role twice and on the 2nd run it ran successfully.

**Comment by jamesalford** [comment]
Okay, I realised that i was using the version from before yesterday which did have the issue
 but tried with the updated one and works fine. 

Thanks for your help

**Comment by nickjj** [comment]
No problem.

Upgrading versions in general should be no problem btw. You could just bump up the version to something newer and re-run the role and it'll provide you the newer version.

**Comment by jamesalford** [comment]
I meant that i was using the old commit so had to pull the latest changes. 
That is great though, should be easy enough to change version. 
Cheers

**Comment by nickjj** [comment]
Closing this as it's resolved.
