### ISSUE TITLE
No package matching 'docker-ce' is available

### ISSUE THREAD

**Issue by smacz42** [nickjj/ansible-docker#58]
## Expected Behavior

All packages required for docker are installed.

## Actual behavior

TASK [docker : Install Docker] ***************************************************************************************************************************************************************************************************************
fatal: [example.com]: FAILED! => {"changed": false, "msg": "No package matching 'docker-ce' is available"}

### Manual test

```
root@manager-test:~# apt install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  docker-ce-cli:amd64

E: Package 'docker-ce' has no installation candidate
```

## Workaround

`apt install docker-ce-cli`

## EDIT

Host OS: Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-154-generic i686)

**Comment by nickjj** [comment]
Have you run `apt-get update` on your host at least once before running this role?

**Comment by smacz42** [comment]
Yes. This failed initially, I SSH'd into the server, ran an apt-get update and retried the role with the same result.

This behavior was not present a week or so ago. Docker might have changed their naming scheme for their Ubuntu packaging.

On July 19, 2019 2:57:09 PM EDT, Nick Janetakis <notifications@github.com> wrote:
>Have you run `apt-get update` on your host at least once before running
>this role?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nickjj/ansible-docker/issues/58#issuecomment-513339708

-- Andrew Cziryak
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nickjj** [comment]
Looks like something recently changed but `docker-ce` should still be available according to https://docs.docker.com/install/linux/docker-ce/ubuntu/.

Seems like maybe they decided to split `docker-ce` and `docker-ce-cli` into 2 packages where the first one is the daemon where as the second one is the client.

**Comment by nickjj** [comment]
I'm not convinced there's an issue with the role.

The role is running to completion for me on Ubuntu 16.04 with no extra things being done outside of this role other than doing standard things you would do on a host such as enabling third party apt repos.

When you ran the role, did the tasks that set up Docker's repo run successfully?

**Comment by smacz42** [comment]
It did. I'll attempt a redeploy today and see if anything changes.

On July 20, 2019 8:45:02 AM EDT, Nick Janetakis <notifications@github.com> wrote:
>I'm not convinced there's an issue with the role.
>
>The role is running to completion for me on Ubuntu 16.04 with no extra
>things being done outside of this role other than doing standard things
>you would do on a host such as enabling third party apt repos.
>
>When you ran the role, did the tasks that set up Docker's repo run
>successfully?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nickjj/ansible-docker/issues/58#issuecomment-513464513

-- Andrew Cziryak
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by smacz42** [comment]
Well, I have it in the scrollback of my terminal, and have made sure my playbooks are at the same revision as yesterday, but I'm no longer seeing the error. I'll let you know if this comes up again, but I'm no longer seeing this issue. Thanks for taking the time to look into it.

**Comment by smacz42** [comment]
FWIW, I ran into the same issue today, and think i'm looking at PEBCAK. I deployed a DO droplet that was 32 bit and ran into this error. Once I deployed a 64 bit image, it worked just fine.
