### ISSUE TITLE
Playing with daemon.json

### ISSUE THREAD

**Issue by rong0312** [nickjj/ansible-docker#62]
Hey,
I find this solution very useful! so, first of all, thank you.

My problem starts when I try to change configs that normally would be located under
daemon.json. For example:

```
{
  "experimental": true,
  "hosts": ["fd://", "tcp://0.0.0.0:2375"]
}
```

I tried to change 'docker__systemd_override' and even 'docker__daemon_json' variables under **defaults.main.yml** file with no success (didnt see daemon.json creation or override yml file for system.d).
I tried to follow the readme instructions. What do I miss?

**Comment by nickjj** [comment]
Hi,

What did you set exactly in your playbook / inventory to customize `docker__daemon_json`?

It should look like this:

```yml
docker__daemon_json: |
  "experimental": true,
  "hosts": ["fd://", "tcp://0.0.0.0:2375"]
```

**Comment by rong0312** [comment]
I have changed the 'docker__daemon_json' variable as you wrote under 'defaults' folder (main.yml).
I did not put anything special inside my playbook- only activated the role.
Do I have to specify some thing?

**Comment by nickjj** [comment]
Did you run my role or your forked copy?

Typically you wouldn't modify files directly in a role. You would modify them by overriding variables in your inventory.

**Comment by rong0312** [comment]
I totally forgot that I have changed a few things in task's yml to make it work with centos as well.
I changed back to your tasks but received that when running the playbook.

```
Sep 03 06:13:21 ip-10-2-11-24 systemd[1]: docker.service: Start request repeated too quickly.
Sep 03 06:13:21 ip-10-2-11-24 systemd[1]: Failed to start Docker Application Container Engine.
Sep 03 06:13:21 ip-10-2-11-24 systemd[1]: docker.service: Unit entered failed state.
Sep 03 06:13:21 ip-10-2-11-24 systemd[1]: docker.service: Failed with result 'start-limit-hit'.
```

I'm pretty sure it's related to the altered daemon.json
Did it happen to you?

**Comment by nickjj** [comment]
What does your `/etc/docker/daemon.json` look like on your server? Paste it here.

Also what does `journalctl` say about that failing Docker service?

I have not encountered that while modifying that file.

If you take a look at the tests for this role, I made a bunch of changes to various config files. You can see that playbook here: https://github.com/nickjj/ansible-docker/blob/master/tests/test.yml

If I were to guess, it's probably a conflict with the `hosts` in the daemon.json config file conflicting with the one in the unit file. For a long time Docker didn't allow you to set `hosts` in daemon.json, but now I think they might let you, but you can't have it defined in 2 different configs.

Try keeping your custom json but set `docker__daemon_flags` to `[]`.

**Comment by rong0312** [comment]
my daemon.json:
```
{
  "log-driver": "journald"
,  "experimental": true,
  "hosts": ["fd://", "tcp://0.0.0.0:2375"]

}
```

journalctl:
```
-- Unit docker.service has begun starting up.
Sep 03 11:33:37 ip-10-2-11-24 dockerd[6614]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: hosts: (from flag: [unix://], fr
Sep 03 11:33:37 ip-10-2-11-24 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 11:33:37 ip-10-2-11-24 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
```
&
```
-- The start-up result is done.
Sep 03 11:33:40 ip-10-2-11-24 systemd[1]: docker.service: Start request repeated too quickly.
Sep 03 11:33:40 ip-10-2-11-24 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
Sep 03 11:33:40 ip-10-2-11-24 systemd[1]: docker.socket: Unit entered failed state.
Sep 03 11:33:40 ip-10-2-11-24 systemd[1]: docker.service: Unit entered failed state.
Sep 03 11:33:40 ip-10-2-11-24 systemd[1]: docker.service: Failed with result 'start-limit-hit'.
```

i guess this is the problem, even due the fact this is my new playbook:

```
---
- hosts: "{{ host_var | default('test-ubuntu') }}"
  remote_user: "{{ user_var | default('ubuntu') }}"
  become: true
  gather_facts: yes

  vars:
    docker__daemon_json: |
      "experimental": true,
      "hosts": ["fd://", "tcp://0.0.0.0:2375"]

    docker__daemon_flags: []

  roles:
    # - ansible-users
    # - machine-install
    - ansible-docker
```

**Comment by nickjj** [comment]
The error says it all:

`Sep 03 11:33:37 ip-10-2-11-24 dockerd[6614]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: hosts: (from flag: [unix://]`

That means you haven't ran what you have defined in your playbook, or those vars aren't taking effect in your playbook.

**Comment by rong0312** [comment]
Did i run them incorrectly?

**Comment by nickjj** [comment]
No, it looks good.

But the error you pasted doesn't line up to what you have in the playbook you pasted.

The error says you have `hosts` defined in both your json file and the daemon flag and it even goes as far as saying it's using `unix://` as the value, which is the default `docker__daemon_flags` value from this role, which makes me think your variables aren't being used due to reasons unknown.

Maybe you're not running that playbook, maybe you forgot to save the playbook, maybe you're checking the results on the wrong server. It's hard to say.

**Comment by rong0312** [comment]
Ok nick ill take your opinion. I will keep trying to figure out what's going on.
Thank you for your time!

**Comment by nickjj** [comment]
It's been a couple of months and I haven't heard anything back, so I'm guessing this is fixed? Going to close this for now.
