### ISSUE TITLE
docker environment mangled

### ISSUE THREAD

**Issue by tyldum** [nickjj/ansible-docker#64]
This change causes my runs to miss the first and last quote.

https://github.com/nickjj/ansible-docker/commit/02d635370297c0df043a88ffc99b9b747743ee06#diff-aeddd16345c3d33656d19cf55fceff3d

**Comment by nickjj** [comment]
Can you show me an example of what the output looks like on your end and what you would expect to see instead?

**Comment by tyldum** [comment]
Got:
```
# Ansible managed

[Service]
Environment=HTTP_PROXY=http://proxy.corp:3128" "HTTPS_PROXY=http://proxy.corp:3128" "NO_PROXY=127.0.0.1/8
```
Expected (and got this by reversing the change):
```
# Ansible managed

[Service]
Environment="HTTP_PROXY=http://proxy.corp:3128" "HTTPS_PROXY=http://proxy.corp:3128" "NO_PROXY=127.0.0.1/8"
```

**Comment by tyldum** [comment]
variable:
```
docker__daemon_environment:
  - "HTTP_PROXY=http://proxy.corp:3128"
  - "HTTPS_PROXY=http://proxy.corp:3128"
  - "NO_PROXY=localhost,127.0.0.1/8"
```

**Comment by nickjj** [comment]
I'm able to confirm that here and funny enough systemd is ok with quote mismatches so it didn't prevent the Docker daemon from starting up.

I just re-worked the template to generate multiple environment variables to be more clear by outputting each one on their own line and to avoid any quote shenanigans.

Can you double confirm it works for you by changing `templates/etc/systemd/docker.service.d/environment.conf.j2` to:

```jinja
# {{ ansible_managed }}

[Service]
{% for env in docker__daemon_environment %}
Environment="{{ env }}"
{% endfor %}
```

It should produce this output:

```
# Ansible managed

[Service]
Environment="HTTP_PROXY=http://proxy.a.com:80"
Environment="HTTPS_PROXY=https://proxy.a.com:443"
```

With an input of:

```yml
docker__daemon_environment:
  - "HTTP_PROXY=http://proxy.a.com:80"
  - "HTTPS_PROXY=https://proxy.a.com:443"
```

**Comment by tyldum** [comment]
It works!
Actually the single line appeared to work as well, but this is the correct way anyways.

**Comment by nickjj** [comment]
Cool.

Yeah if the quotes were lined up it should have worked on 1 line in the end.

I just pushed v1.9.1 to the Galaxy with this fix and here's the commit: https://github.com/nickjj/ansible-docker/commit/beaaccb323f8fe3738fd2a00b386ea21874caf22
