### ISSUE TITLE
"Manage Docker registry login credentials" shouldn't ouput log. 

### ISSUE THREAD

**Issue by Pjirlip** [nickjj/ansible-docker#68]
First thanks for this role! :-) 

One "little" security issue here:
### 1: The Task:  Manage Docker registry login credentials shouldn't log the output, obviously because there are credentials displayed. 

Example: 
> TASK [nickjj.docker : Manage Docker registry login credentials] *********************************************************************************************************************
changed: [<CENSORED>] => (item={u'username': u'<CENSORED>', u'reauthorize': True, u'state': u'present', u'password': u'<CENSORED>', u'email': u'<CENSORED>', u'registry_url': u'<CENSORED>'})

Of course i could set "no_log: true" in the playbook but then i don't have any log of the task at all, which is also not optimal.

Please set "no_log: true" on the task itself. Thanks

**Comment by nickjj** [comment]
Hi,

Thanks.

I believe if you run Ansible with debug mode on the `no_log` tasks will still show up, so I'm not sure if that's a viable solution because in the end the data can still be exposed.

**Comment by nickjj** [comment]
I'm going to close this since the `no_log` option doesn't offer any additional protection. If you can think of a different solution please re-open it.
