### ISSUE TITLE
ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}" and python3

### ISSUE THREAD

**Issue by shadow1runner** [nickjj/ansible-docker#83]
Hi,

I've got two servers:

* infra1: running Ubuntu 20.04 LTS, defaults to python3, by using the workaround I mentioned in #82 
* infra2: running Ubuntu 18.04 LTS, defaults to python2

When running the very same ansible playbook, I'm running into issues while trying to configure private docker registries on 20.04 (as no previous step makes use of `ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"`, but all which do suffer the same issue):

```
TASK [nickjj.docker : Manage Docker registry login credentials] *********************************************************************************************************************************************************************failed: [infra1] (item={u'username': u'***', u'password': u'***', u'registry_url': u'****'}) => {"ansible_loop_var": "item", "changed": false, "item": {"password": "***", "registry_url": "****", "username": "***"}, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on infra1's Python /usr/local/bin/python-docker. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'"}
changed: [infra2] => (item={u'username': u'***', u'password': u'***', u'registry_url': u'****'})
failed: [infra1] (item={u'username': u'***', u'password': u'***', u'config_path': u'***/.docker/config.json', u'registry_url': u'****'}) => {"ansible_loop_var": "item", "changed": false, "item": {"config_path": "***/.docker/config.json", "password": "***", "registry_url": "****", "username": "***"}, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on infra1's Python /usr/local/bin/python-docker. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'"}
changed: [infra2] => (item={u'username': u'***', u'password': u'***', u'config_path': u'***/.docker/config.json', u'registry_url': u'****'})
```

This made me curious and I wanted to dig deeper:

#### infra2 (python 2, Ubuntu 18.04 LTS) -> OK

```shell
$ ll /usr/local/bin/python-docker
lrwxrwxrwx 1 root root 43 May 11 22:32 /usr/local/bin/python-docker -> /usr/local/lib/docker/virtualenv/bin/python*
$ ll /usr/local/lib/docker/virtualenv/bin/python
lrwxrwxrwx 1 root root 7 May 11 22:31 /usr/local/lib/docker/virtualenv/bin/python -> python2*
$ python-docker
Python 2.7.17 (default, Apr 15 2020, 17:20:14)
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', '/usr/local/lib/docker/virtualenv/lib/python2.7', '/usr/local/lib/docker/virtualenv/lib/python2.7/plat-x86_64-linux-gnu', '/usr/local/lib/docker/virtualenv/lib/python2.7/lib-tk', '/usr/local/lib/docker/virtualenv/lib/python2.7/lib-old', '/usr/local/lib/docker/virtualenv/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/local/lib/docker/virtualenv/local/lib/python2.7/site-packages', '/usr/local/lib/docker/virtualenv/lib/python2.7/site-packages']
>>> import docker
>>> 
```

#### infra1 (python 3, Ubuntu 20.04 LTS) -> NOK

```shell
$ which python-docker
/usr/local/bin/python-docker
$ ll /usr/local/bin/python-docker
lrwxrwxrwx 1 root root 43 May 11 22:32 /usr/local/bin/python-docker -> /usr/local/lib/docker/virtualenv/bin/python*
$ ll /usr/local/lib/docker/virtualenv/bin/python
lrwxrwxrwx 1 root root 16 May 11 22:31 /usr/local/lib/docker/virtualenv/bin/python -> /usr/bin/python3*
$ python-docker
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
>>> import docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'docker'
>>> exit()
$ source /usr/local/lib/docker/virtualenv/bin/activate
(virtualenv) $ python
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> import sys
>>> print(sys.path)
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/docker/virtualenv/lib/python3.8/site-packages']
```

So it seems that either the change to python3 or Ubuntu 20 changed the way they are importing paths in virtual environments: the `/usr/local/lib/docker/virtualenv/lib/python3.8/site-packages` are only included when I activate the venv directly.
I know it's not necessarily an issue with this ansible role, but have you experienced something similar before? (I'll also continue searching of course, but not tonight :D)

Thanks!

**Comment by shadow1runner** [comment]
Or could it be that the role requires changes like in https://github.com/nickjj/ansible-docker/pull/75/files#diff-2444ad0870f91f17ca6c2a5e96b26823?

**Comment by nickjj** [comment]
Hi,

Have you tried using the master branch of this role instead of the latest pushed release?

I believe this likely stems from you having an older 18.04 server that was provisioned a while back which uses an older version of virtualenv.

But newer versions of virtualenv broke using symlinks. So the fix is to apt install virtualenv instead of pip installing it, and even Ubuntu 20.04 should have an old enough version of virtualenv where you should be safe.

**Comment by shadow1runner** [comment]
Thank you for your help; unfortunately it didn't work; here's what I did:

```bash
ansible-galaxy remove nickjj.docker # not really necessary, but still
ansible-galaxy install git+https://github.com/nickjj/ansible-docker.git,master
```

Manually edited the playbook to use the new role (using the output of `ansible-galaxy list` -> `role: ansible-docker, master`) and then I've started over with two new VMs, still the result is the same as before:

```bash
/usr/bin/env python-docker
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'docker'
>>> import sys
>>> print(sys.path)
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
```

> The master branch patched things to use apt to install virtualenv

Interestingly enough though, neither can I [find the role doing the installation](https://github.com/nickjj/ansible-docker/blob/master/tasks/main.yml), nor do I see it in the ansible output while running the playbook; still, trying to install `virtualenv` on Ubuntu 20.04 shows no changes (also because first thing my role does is to update all packages on the new system):

```bash
sudo apt install virtualenv 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
virtualenv is already the newest version (20.0.17-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Any other hints/anything I did wrong or misunderstand?
Thanks a lot for the help btw

**Comment by nickjj** [comment]
Ah I see the issue. Ubuntu 20.04 comes with virtualenv 20.0.17 which has the symlink bug. When Googling for Ubuntu 20.0.4 virtualenv apt version some of the first hits were for Ubuntu 19.x which has an older version that was safe.

I guess a proper fix will need to be put in place to get around the symlink issue. Basically it will involve not using the symlink. It's kind of inconvenient but the author of virtualenv said it's due to the venv package no longer supporting it.

**Comment by shadow1runner** [comment]
Thanks for the hint, now it works.
Please have a look at the PR I've just opened; at least all CI tests pass, but I'm quite sure many users of this role won't be too happy with the change, what do you think?

**Comment by nickjj** [comment]
Yeah I think removing it might not be the right play. Ideally I'd like to not change anything from the role / documentation level and get things to work the same as they did before except instead of making a symlink, you can make a proxy script.

Basically a bash script that does nothing except call the full binary path but pass in `$@` to forward any arguments. I'll take care of this PR, don't worry about it.

**Comment by nickjj** [comment]
This has been addressed on master.

I'll push a new release once Docker officially supports 20.04.

**Comment by shadow1runner** [comment]
Thanks for your work on this, I've just tried with your master branch and it is working fine 👍
