### ISSUE TITLE
Add default varaibles

### ISSUE THREAD

**Issue by ArtemBernatskyy** [nickjj/ansible-docker#9]
I think we need to add predefined default variables to allow user kick start installation without any additional configuration )

**Comment by nickjj** [comment]
You shouldn't need to configure anything extra to have everything work. Just by calling the role with its current defaults you should end up with the latest Docker / Docker Compose installed and a cron job to deal with Docker related maintenance.

What held you back from it all working automatically?

**Comment by ArtemBernatskyy** [comment]
There are a couple of predefined variables but

`TASK [nickjj.docker : Configure upstream APT repository] ****************************************************************************************************************************
fatal: [default]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: deb [arch=amd64] https://download.docker.com/linux/{{ docker_distribution | lower }} {{ docker_distribution_release }} {{ docker_channel }}: {{ ansible_local.core.distribution_release if (ansible_local|d() and ansible_local.core|d() and ansible_local.core.distribution_release|d()) else ansible_distribution_release }}: 'ansible_distribution_release' is undefined\n\nThe error appears to have been in '/Users/artem/.ansible/roles/nickjj.docker/tasks/main.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Configure upstream APT repository\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: deb [arch=amd64] https://download.docker.com/linux/{{ docker_distribution | lower }} {{ docker_distribution_release }} {{ docker_channel }}: {{ ansible_local.core.distribution_release if (ansible_local|d() and ansible_local.core|d() and ansible_local.core.distribution_release|d()) else ansible_distribution_release }}: 'ansible_distribution_release' is undefined"}
`

as u can see there are a lot of not predefined variables

**Comment by nickjj** [comment]
I can't say for sure but that sounds like maybe you ran the playbook without gathering facts.

You'll need to `gather_facts: True` for those `ansible_*` variables to be defined.

**Comment by ArtemBernatskyy** [comment]
Yes you r right ( I'll close this issue

**Comment by ArtemBernatskyy** [comment]
For those with similar situation when you don't want to gather facts at the beginning you can use this task, it will gather facts at that specific point
  
```
- name: Gathering facts
  setup:
```
