### ISSUE TITLE
No package matching 'gcc' is available

### ISSUE THREAD

**Issue by ahkhystrix** [nickjj/ansible-docker#90]
Hello!

I installed cloud machine on Hetzner with Ubuntu 18.04 and tried to install docker.
I got an error:
```
TASK [nickjj.docker : Install Docker's dependencies] ***************************
fatal: [95.217.165.205]: FAILED! => {"changed": false, "msg": "No package matching 'gcc' is available"}
```

I updated packegs on system:
`apt update`

After that, the installation was successful.

```
ansible-galaxy list
# /home/hystrix/.ansible/roles
- nickjj.docker, v2.0.0
```

**Comment by nickjj** [comment]
Hi,

Thanks. Check this comment out for more details https://github.com/nickjj/ansible-docker/issues/89#issuecomment-633207847.
