### ISSUE TITLE
JFYI: unable to use docker_ ansible modules with virtualenv

### ISSUE THREAD

**Issue by frisbee23** [nickjj/ansible-docker#91]
debian10 (which has python2 and python3, sadly..)

tried this in another role:
- name: Create db container and connect to network
  docker_container:
    name:
    image: "postgres:latest"
    volumes:
      - /var/run/postgresql
      - /usr/share/postgresql
      - /var/lib/postgresql/data
      - /tmp
    networks:
      - name: "mattermost-docker_default"
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"

==> error:
TASK [XXX: Create db container and connect to network] *******************************************************************************
fatal: [XXX]: FAILED! => {"changed": false, "module_stderr": "Shared connection to XXX.tld closed.\r\n", "module_stdout": "/usr/local/bin/python3-docker: line 3: /usr/local/lib/docker/virtualenv/bin/python3: No such file or directory\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}

the virtual env was only "featuring" python2

this is no real bug for me. just for your ( or others  ) information.
im trying to escape python2 vs 3 hell by using ubuntu now instead of debian.

**Comment by nickjj** [comment]
Hi,

Thanks. If you install Python 3 on Debian you should be good to go btw.
